### ISSUE TITLE
allwinner device

### ISSUE THREAD

**Issue by kokenot** [ophub/amlogic-s9xxx-openwrt#126]
do you have any guide on how to compile allwinner firmware? can this script use to compile allwinner device?

**Comment by ophub** [comment]
For non-Amlogic builds, it is recommended to use flippy's repo for packaging: [openwrt_packit](https://github.com/unifreq/openwrt_packit). 

```
- name: Package Armvirt as OpenWrt
  uses: unifreq/openwrt_packit@master
  env:
    OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
    PACKAGE_SOC: s905d_s905x3_beikeyun_vplus_l1pro
    KERNEL_VERSION_NAME: 5.10.66_5.4.147
```
